### PR TITLE
Lidar guidance

### LINKED ISSUE #15: Basic automatic driving
As a user, I want the car to drive autonomously after detecting a close object, so that the car does not find an obstacle and stop.

Acceptance criteria:
- The SmartCar continues driving autonomously after detecting an object.

### LINKED ISSUE #19: Initialize the Micro-LIDAR sensors.
As a user, I want a fast and reliable way to measure the distance to obstacles, so i don't crash with the car.

Acceptance criteria:
- The car should measure and sense obstacles in its path.

### PR DESCRIPTION
**Pull request by Brother-Blue**
Basic automation should be finished. Still requires physical tests.

Fixes issues #15 and #19.

### CODE REVIEW

**Comment by linusaaberg** [comment]
You have used the GP2Y0A21 in the code which we dont have access to. Use the Micro-LIDAR. (DIT112 platform_workshop slide 53)

**Review by linusaaberg — CHANGES_REQUESTED** [review]
And we might need to still use the Ultrasonic sensor?. We will only use one Micro_LIDAR due to the problem addressed by Dimitrios. So we could use the micro-LIDAR to check to front and use the ultrasonic for the sides or something like that.

**Comment by Brother-Blue** [comment]
Ultrasonic sensor was re-implemented to measure distance from the back side of the car now. Pins may need to be changed, everything that is marked with a FIXME needs to be checked by Linus Å since those require physical testing.

**Comment by linusaaberg** [comment]
I have a hard time understanding parts of the code.
On line 25 you declare const int SIDE_FRONT_PIN = A0 and asks for a pin checkup. 
What is this pin used for?

Also, you never run the code Wire.begin() to join the I2C bus as a master for the sensor in setup().

**Comment by Brother-Blue** [comment]
The comment by the pin was not updated, it is now for the Micro-LIDAR sensor. As we do not have the car we are not able to properly specify which pin it is connected to hence the checkup request. Wire.begin() is in the setup() method now too.

**Comment by linusaaberg** [comment]
The problem was not the comment, the problem was that the pin is never used. It is just declared. I don't think we need to declare a pin for the LIDAR sensor. At least I have not found a case where it is needed for the pololu library. Maybe @platisd can confirm this?

**Comment by linusaaberg** [comment]
I tried the code on the car. It just keeps running when it finds obstacle at the moment. I put in a Serial printer for the LIDAR to see what it said and it just reads 8190 continuously no matter the distance.

**Comment by Hjalmar-Thunberg** [comment]
Test with latest commit, found some  wrong variables when trying to turn around an obstacle.

**Comment by linusaaberg** [comment]
Car backs away from obstacle at the moment. But doesn't behave as expected. Will accept the merge so we can improve next week.

**Review by linusaaberg — APPROVED** [review]

**Pull request merged**
