### PR TITLE
Implemented smartcar class

### LINKED ISSUE #10: Implement Smartcar class
As a user I want to make use of the functions contained in the Smartcar class.

Acceptance Criteria:
- The car should run on a 'SmartCar' class.

### PR DESCRIPTION
**Pull request by Hjalmar-Thunberg**
Implemented and changed previous "SimpleCar" class to" SmartCar" class. Fixes #10

### CODE REVIEW

**Comment by LinusAaberg** [comment]
Should we not make use of both of the odometers we have on the car? Both left and right?

**Review by linusaaberg — COMMENTED** [review]
Should we not make use of both of the odometers we have on the car? Both left and right?

**Comment by Hjalmar-Thunberg** [comment]
> Should we not make use of both of the odometers we have on the car? Both left and right?

The odometer checks the distance traveled of the motor, both sides should result in the same amount. Therefore only one side was included.

**Comment by platisd** [comment]
> both sides should result in the same amount.

:giggles 

You'll be surprised! :grin:

**Review by linusaaberg — APPROVED** [review]
You can merge

**Pull request merged**
