### PR TITLE
Autodriving tweaks

### PR DESCRIPTION
**Pull request by linusaaberg**
Okay so I'm going insane here. The code worked perfect the first couple of tests I did this morning. When I then tried it again it didn´t work. I have tried reverting the code back to the one we had when we showed the demo-video which doesn´t work anymore either.

I have a small concern that the problem is the LIDAR sensor. 
``` c++
void automatedDriving()
{
    //Drive forward until there is an obstacle infron of car.
    driveForward(); 
    while(autoDrivingEnabled){
        checkFrontObstacle();
        if(!atObstacleFront)
        {
            driveForward();
            checkFrontObstacle();
        }
        else
        {
            checkLeftObstacle();
            checkRightObstacle();

            if (!atObstacleLeft && atObstacleRight){ rotateOnSpot(LEFT);} // If obstacle at right but not left, turn left.
            else if(!atObstacleLeft && !atObstacleRight){ rotateOnSpot(RIGHT);} // If both sides are clear, turn right.
            else if(atObstacleLeft  && !atObstacleRight){ rotateOnSpot(RIGHT);} // If obstacle at left but not right, trun right.
            //else if(atObstacleLeft  && atObstacleRight){ driveDistance(30, -SPEED);} 
        }
    }
}
```

When we enter the function the car drives forward until it reaches an obstacle and then it turns the desired way. But then it goes bananas. After the turn, if we look at the code it should go back to checkFrontObstacle() and if it is clear it should drive forward until it reaches the next obstacle and turn accordingly. What the car does instead is to just turn back and forth on the spot, and after a while it drives forward. It feels like the LIDAR sensor is not picking up the distance to correctly
change the boolean. So we dont enter the if(!atObstacleFront) again.

I have tried with delays and other stuff. Sometimes it works, and sometimes it doesn´t. Can you see any problem @platisd  because I'm about to loose my mind here.

### CODE REVIEW

**Comment by platisd** [comment]
That particular piece of code looks fine in theory. However in the real world there is **noise**.

>  It feels like the LIDAR sensor is not picking up the distance to correctly change the boolean.

Why don't you look then more into the values the LIDAR returns when the strange behavior is seen?

Btw all these inline-if expressions can be simplified:

```cpp
atObstacleFront = (frontDistance > 0 && frontDistance <= FRONT_MIN_OBSTACLE) ? true : false;
```
To:
```cpp
atObstacleFront = frontDistance > 0 && frontDistance <= FRONT_MIN_OBSTACLE
```

**Comment by linusaaberg** [comment]
Okay, so I added some bluetoothe.println to check the distance. After the cars first turn and after driving forward the LIDAR sensor picks up very small values from 1 - 10 mm (which will indicate that there is an obstacle ahead) while I have been trying now. Will change the code and keep that in mind and see if I can get the result I want.

**Comment by linusaaberg** [comment]
Okay so I have tried to fix it but it wont work because the readings are all over the place, it reads 8190mm one time, then it drops to 0, goes to 37, goes up to 200 and so on. I have tried to change LIDAR sensor without success, and also tried to change how often the sensor should update the readings. Since the jumping values are so unpredictable I think we will have to go without the LIDAR, and just go with one Ultrasonic sensor. Will be alot of turning around but I cant see any other workaround. 

I have no ide why it does like this, but I can really not see any way to solve it. It feels like the Sensors are faulty or just to unstable for our cause.

**Comment by platisd** [comment]
> I have no ide why it does like this, but I can really not see any way to solve it. It feels like the Sensors are faulty or just to unstable for our cause.

The sensors are surely **not** faulty. Your (idealistic) expectations of them combined with *how* you use them are though. :)
In fact, these sensors are on the higher end of hobby-grade sensors, used in applications such as these miniature [self-driving racing cars](https://www.youtube.com/watch?v=7ZGcnNBZ6tk).

As I mentioned before, the real world is noisy. Interpreting this non-ideal, noisy, constantly changing world by being reliant on a single source of (a single!) measurement is risky, no matter how expensive your hardware is. That is why we use software/logic to make sense of the readings, filter faulty ones etc.

In your case, you could also try these:
1. In the [VL53L0X example](https://github.com/pololu/vl53l0x-arduino/blob/master/examples/Single/Single.ino), they use the following to increase the sensor's accuracy on the expense of speed:

```cpp
  // increase timing budget to 200 ms
  sensor.setMeasurementTimingBudget(200000);
```

I don't know if this is equivalent to the `startContinuous(100)` you are using but it's something to look more into. Just make sure you don't make your sensors too slow.
2. When there is a timeout, a large invalid value is returned, i.e. `8190` and **not** `0` like the ultrasonic sensors do. Make sure this doesn't affect your logic.

**Comment by linusaaberg** [comment]
So I have read around a bit on forums and such for the sensor, and one thing I have noticed when it comes to the wrong readings is the protective film on the laser. It is stated that this should be removed in order to get the proper result. I have not noticed this protective film before and I don't want to remove it before checking in with you.
They mention the film [here](https://diyprojects.io/hc-sr04-ultrasound-vs-sharp-gp2y0a02yk0f-ir-vl53l0x-laser-solutions-choose-distance-measurement-arduino-raspberrypi/#.Xr_UEcBS-Uk) and [here](https://forum.pololu.com/t/vl53l0x-noisy-problem-in-air-garp/11500/5)

**Comment by platisd** [comment]
When I got the sensors, they had a protective film on them that may or may not have been removed by me before handing them over. If there is one, feel free to remove it. :+1:

**Comment by linusaaberg** [comment]
Added a median-filter to get more reliable results from the LIDAR sensor readings. Removed the protective-film from sensor so the readings are now more correct overall aswell. The car behaves as expected. 
Fixes #38.

**Comment by platisd** [comment]
Very nice, glad to hear! :+1:

**Review by linusivarssons — APPROVED** [review]
Looks good

**Pull request merged**
