### PR TITLE
Add Car Control to the SmartCar

### LINKED ISSUE #3: Car steering
As a Driver, I want to be able to steer the car, so that I can navigate it properly.

Acceptance Criteria:
- The car can move forward, backwards, right and left.

### PR DESCRIPTION
**Pull request by clementinejensen**
Add the necessary implementation for the SmartCar
to be controlled through input.
Add the handleInput method, constants for speed,
and turning degrees.

As a result, the car should be able to
be controlled through input.

Fixes #3

### CODE REVIEW

**Comment by clementinejensen** [comment]
Fixes #3

**Review by platisd — COMMENTED** [review]
Looks good, but why was I added as a reviewer? :sweat_smile:

**Comment by LinusAaberg** [comment]
(Y)

**Review by linusaaberg — COMMENTED** [review]
(Y)

**Review by linusaaberg — APPROVED** [review]

**Pull request merged**
